GET http://localhost:9080/cs-go/api/users

###

GET http://localhost:9080/cs-go/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

GET http://localhost:9080/cs-go/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e

###

GET http://localhost:9080/cs-go/api/users/cc0b0577-bb6f-45b7-81d6-3db88e6ac19f


###

PUT http://localhost:9080/cs-go/api/users/cc0b0577-bb6f-45b7-81d6-3db88e6ac19f
Content-Type: application/json

{
  "login": "mati",
  "birthDate": "2002-01-07",
  "name": "janek",
  "surname": "wesoly",
  "password": "asdsd",
  "email": "sdasd"
}

###

PATCH http://localhost:9080/cs-go/api/users/cc0b0577-bb6f-45b7-81d6-3db88e6ac19f
Content-Type: application/json

{
  "login": "janeczek",
  "birthDate": "1999-09-09",
  "name": "janek",
  "surname": "smutny",
  "password": "mocnehaslo",
  "email": "sieeema"
}

###

#DELETE http://localhost:9080/cs-go/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197

###

GET http://localhost:9080/cs-go/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar

###

GET http://localhost:9080/cs-go/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar


###

PUT http://localhost:9080/cs-go/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="sigrid.png'

< src/main/resources/test/avatar/sigrid.png
--boundary--

###

PATCH http://localhost:9080/cs-go/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="zereni.png'

< src/main/resources/test/avatar/zereni.png
--boundary--

###

DELETE http://localhost:9080/cs-go/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar